title: Among us Blog
author: TheChickenKnight
email: chcknknight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima

# social links
twitter_username: TheChickenKnight # DO NOT include the @ character, or else the build will fail!
github_username:  TheChickenKnight # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
