title: About Me
author: TheChickenKnight
email: chcknknight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My About Me page!
theme: minima

# social links
twitter_username: TheChickenKnight # DO NOT include the @ character, or else the build will fail!
github_username:  TheChickenKnight # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
